networks:
  roboshop:
    external: true

services:
  mongodb:
    image: mongodb:1.0
    container_name: mongodb
    networks:
      - roboshop
  catalogue:
    image: catalogue:1.0
    container_name: catalogue
    networks:
      - roboshop
    depends_on: 
      - mongodb
  web:
    image: web:1.0
    container_name: web
    networks:
      - roboshop
    ports:
      - "80:80"
    depends_on: 
      - mongodb
      - catalogue
      - user
      - cart
      - redis
      - shipping
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - roboshop
  user:
    image: user:1.0
    container_name: user
    networks:
      - roboshop
    depends_on:
      - redis
      - mongodb
  cart:
    image: cart:1.0
    container_name: cart
    networks:
      - roboshop
    depends_on:
      - redis
      - catalogue
  mysql:
    image: mysql:1.0
    container_name: mysql
    networks:
      - roboshop

  shipping:
    image: shipping:1.0
    container_name: shipping
    networks:
      - roboshop
    depends_on:
      - mysql

    

