networks:
  roboshop:
    external: true

services:
  mongodb:
    image: mongodb:1.0
    networks:
      - roboshop
  catalogue:
    image: catalogue:1.0
    networks:
      - roboshop
    depends_on: 
      - mongodb
  web:
    image: web:1.0
    networks:
      - roboshop
    ports:
      - "80:80"
    depends_on: 
      - mongodb
      - catalogue
      - user
      - cart
      - redis
  redis:
    image: redis:latest
    networks:
      - roboshop
  user:
    image: user:1.0
    networks:
      - roboshop
    depends_on:
      - redis
      - mongodb
  cart:
    image: cart:1.0
    networks:
      - roboshop
    depends_on:
      - redis
      - catalogue

