version: "3.8"  # Add version to specify Compose file format

networks:
  roboshop:
    external: true

services:
  mongodb:
    image: mongodb:1.0
    networks:
      - roboshop
  catalogue:
    image: catalogue:1.0
    networks:
      - roboshop
    depends_on: 
      - mongodb
  web:
    image: web:1.0
    networks:
      - roboshop
    ports:
      - "80:80"
    depends_on: 
      - mongodb
      - catalogue
